# These are supported funding model platforms

github: [chekos, tacos-de-datos] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: tacosdedatos # Replace with a single Patreon username
custom: ["https://anchor.fm/tacosdedatos", "https://anchor.fm/quaildata"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
